### ISSUE TITLE
Plugin disabled when running on 1.19.3

### ISSUE THREAD

**Issue by aisukuma** [Gaming32/StrongholdConfig#1]
The plugin does not work after dropping it in the plugins folder. I did add the required JVM argument to my startup flags as well.

```
[18:19:51 WARN]: java.lang.RuntimeException: Unable to load StrongholdModifier
[18:19:51 WARN]:        at StrongholdConfig-1.0.0.jar//com.jemnetworks.strongholdconfig.StrongholdModifier.failIfUnloaded(StrongholdModifier.java:82)
[18:19:51 WARN]:        at StrongholdConfig-1.0.0.jar//com.jemnetworks.strongholdconfig.StrongholdConfigPlugin.onEnable(StrongholdConfigPlugin.java:25)
[18:19:51 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[18:19:51 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
[18:19:51 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[18:19:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[18:19:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560)
[18:19:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471)
[18:19:51 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
[18:19:51 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[18:19:51 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[18:19:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:19:51 WARN]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/level/levelgen/StructureSettings
[18:19:51 WARN]:        at StrongholdConfig-1.0.0.jar//com.jemnetworks.strongholdconfig.StrongholdModifier.<clinit>(StrongholdModifier.java:25)
[18:19:51 WARN]:        ... 11 more
[18:19:51 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.level.levelgen.StructureSettings
[18:19:51 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[18:19:51 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[18:19:51 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[18:19:51 WARN]:        ... 12 more
[18:19:51 ERROR]: [StrongholdConfig] Initialization failed, disabling plugin...
```

**Comment by Gaming32** [comment]
This plugin no longer works on modern versions. *However*, Vanilla now supports the functionality of this plugin through the use of datapacks, so you can just make a datapack for this.
